name: PR Creation and Notification Workflow

on:
  push:
    branches:
      - main  # Trigger on push to main branch or you can specify any branch

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Run the script to fetch and save quotes
      - name: Run the script to update quotes
        id: update-quotes
        run: |
          python fetch_quotes.py

      # Run PR creation script
      - name: Create Pull Request
        id: pr_creation
        run: |
          pr_response=$(python create_pr.py)
          echo "Captured PR response: $pr_response"

      # Debug PR Response
      - name: Debug PR Response
        run: |
          echo "Debug: PR Response before condition: '$pr_response'"

      # Send PR response to Telegram using curl
      - name: Send PR response to Telegram using curl
        run: |
          if [ -n "$pr_response" ]; then
            echo "Sending PR Response to Telegram: $pr_response"
            curl -X POST \
              "https://api.telegram.org/bot${{ secrets.BOT_TOKEN }}/sendMessage" \
              -d chat_id="${{ secrets.OWNER_ID }}" \
              -d text="$pr_response"
          else
            echo "Error: PR response is empty or null."
            curl -X POST \
              "https://api.telegram.org/bot${{ secrets.BOT_TOKEN }}/sendMessage" \
              -d chat_id="${{ secrets.OWNER_ID }}" \
              -d text="Error: Pull Request creation failed. Please check the logs for details."
          fi
