name: Automate Weekly Quotes Update

on:
  schedule:
    - cron: '30 13 * * 6'  # Run every Saturday at 7 PM IST (13:30 UTC)
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  update-quotes:
    runs-on: ubuntu-latest
    env:
      API_ID: ${{ secrets.API_ID }}
      API_HASH: ${{ secrets.API_HASH }}
      CHANNEL_USERNAME: ${{ secrets.CHANNEL_USERNAME }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      REPO_OWNER: ${{ secrets.REPO_OWNER }}
      REPO_NAME: ${{ secrets.REPO_NAME }}
      SESSION_STRING: ${{ secrets.SESSION_STRING }}
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}  # Your Telegram bot token
      OWNER_ID: ${{ secrets.OWNER_ID }}  # Your Telegram chat or channel ID
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install telethon requests

      - name: Run the script to update quotes
        id: update-quotes
        run: |
          python fetch_quotes.py
        env:
          SESSION_STRING: ${{ secrets.SESSION_STRING }}  # Pass session string from secrets
          continue-on-error: true # Prevents the job from failing if the script fails

      - name: Check for errors in fetch step
        run: |
          if [ $? -ne 0 ]; then
            echo "Error: Fetch quotes step failed" >> $GITHUB_ENV
            curl -X POST \
              "https://api.telegram.org/bot${{ secrets.BOT_TOKEN }}/sendMessage" \
              -d chat_id="${{ secrets.OWNER_ID }}" \
              -d text="Error: The fetch_quotes.py script failed. Please check the logs for details."
          fi

      - name: Create Pull Request
        id: pr_creation
        run: |
          pr_response=$(python create_pr.py)
          continue-on-error: true

      - name: Send Telegram notification for Pull Request creation
        run: |
          if [ -n "${{ env.PR_CREATED_URL }}" ] && [ -n "${{ env.PR_TITLE }}" ]; then
            python notify.py "${{ env.PR_TITLE }}" "${{ env.PR_CREATED_URL }}"
          else
            curl -X POST \
              "https://api.telegram.org/bot${{ secrets.BOT_TOKEN }}/sendMessage" \
              -d chat_id="${{ secrets.OWNER_ID }}" \
              -d text="Error: Pull Request creation failed. Please check the logs for details."
          fi
        continue-on-error: true

  review-and-merge:
    runs-on: ubuntu-latest
    needs: update-quotes
    steps:
      - name: Notify for review
        run: |
          echo "Pull request created. Please review it manually."
          echo "Once reviewed, you can merge it manually from the GitHub UI."
      
      - name: Send Telegram notification for review
        run: |
          curl -X POST \
            "https://api.telegram.org/bot${{ secrets.BOT_TOKEN }}/sendMessage" \
            -d chat_id="${{ secrets.OWNER_ID }}" \
            -d text="The pull request is ready for your review. Please check and merge manually."
        continue-on-error: true
