name: Automate Weekly Quotes Update

on:
  schedule:
    - cron: '30 13 * * 6'  # Run every Saturday at 7 PM IST (13:30 UTC)
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  update-quotes:
    runs-on: ubuntu-latest
    env:
      API_ID: ${{ secrets.API_ID }}
      API_HASH: ${{ secrets.API_HASH }}
      CHANNEL_USERNAME: ${{ secrets.CHANNEL_USERNAME }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      REPO_OWNER: ${{ secrets.REPO_OWNER }}
      REPO_NAME: ${{ secrets.REPO_NAME }}
      SESSION_STRING: ${{ secrets.SESSION_STRING }}
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}  # Your Telegram bot token
      OWNER_ID: ${{ secrets.OWNER_ID }}  # Your Telegram chat or channel ID
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install telethon requests

      - name: Run the script to update quotes
        id: update-quotes
        run: |
          python fetch_quotes.py
        env:
          SESSION_STRING: ${{ secrets.SESSION_STRING }}  # Pass session string from secrets

      - name: Create Pull Request
        id: pr_creation
        run: |
          pr_response=$(python create_pr.py)
          echo "PR Response: $pr_response"  # This will print the string response

      - name: Send Pull Request creation and review message to Telegram using curl
        run: |
          curl -X POST \
            "https://api.telegram.org/bot${{ secrets.BOT_TOKEN }}/sendMessage" \
            -d chat_id="${{ secrets.OWNER_ID }}" \
            -d text="A pull request has been successfully created and is awaiting your review. Please review and merge it."
          
          echo "Message sent successfully."
